version: '3'
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app # - 왼쪽이 로컬 path : 오른쪽이 컨테이너 속의 path
    command: ["npm", "run", "test"]
    